@URL = http://localhost:4201/
@TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYjA5MTdlZDIxYmIzNDVmYjQ2NDhmZiIsIm5hbWUiOiJUZXN0IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTYyMjE4NDcyOCwiZXhwIjoxNjUzNzQxNjU0fQ.XsBEs0P-DbnKNDr-xaSSkwlBZDNJVnMswubgckPC2Cs

###
POST {{URL}}company/logo/60b29e4a02eccf881f35a0c8 HTTP/1.1
authorization: {{TOKEN}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="1.jpg"; filename="1.jpg"
Content-Type: image/jpg

< ./1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
POST {{URL}}register/signUp/hr HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "user": {
        "email": "test@gmail.com",
        "password": "testtest",
        "password1": "testtest",
        "name": "Test",
        "phone": "1212122"
    }
}

###
POST {{URL}}register/login/hr HTTP/1.1
Content-Type: application/json; charset=utf-8

{
    "user": {
        "email": "test@gmail.com",
        "password": "testtest"
    }
}

###
POST {{URL}}company/company HTTP/1.1
Content-Type: application/json; charset=utf-8
authorization: {{TOKEN}}

{
    "dataToPost": {
        "logo": "filename.png",
        "address": "Ahmedabad",
        "site": "test.com",
        "about": "test"
    }
}

###
GET {{URL}}company/all HTTP/1.1
Content-Type: application/json; charset=utf-8

###
GET {{URL}}company/company/60b087d676b2e039fe48f796 HTTP/1.1
Content-Type: application/json; charset=utf-8
authorization: {{TOKEN}}

###
PUT {{URL}}company/company/:id HTTP/1.1
Content-Type: application/json; charset=utf-8
authorization: {{TOKEN}}

{
    "logo": "filename.png",
    "address": "Ahmedabad",
    "site": "test.com",
    "about": "test"
}

###
DELETE {{URL}}company/company/:id HTTP/1.1
Content-Type: application/json; charset=utf-8
authorization: {{TOKEN}}


